---
- name: Install and configure a Minecraft 1.17 Server  
  hosts: localhost
  vars:
    mc_server_path: /opt/minecraft/oci/
  tasks:
    - name: install needed packages
      ansible.builtin.yum:
        name:
          - screen
          - jdk-16*.aarch64
        state: present
    
    - name: Ensure group minecraft exists
      ansible.builtin.group:
        name: minecraft
        state: present
    
    - name: Add the user 'minecraft' with a primary group of 'minecraft'
      ansible.builtin.user:
        name: minecraft
        comment: Minecraft service account
        group: minecraft

    - name: Add the user 'opc' to the group 'minecraft'
      ansible.builtin.user:
        name: opc
        groups: minecraft
        append: yes
    
    - name:  Create the destination directory for server and related files (setgid to minecraft)
      ansible.builtin.file:
        path:  '{{ mc_server_path }}'
        state: directory
        group: minecraft
        owner: minecraft
        mode: '2770'
        recurse: yes
    
    - name: Download the Minecraft server jar
      get_url:
        url: '{{ MINECRAFT_SERVER_URL }}'
        dest: '{{ mc_server_path }}'
        mode: '0770'
      become: yes
      become_user: minecraft
    
    - name: open needed ports on host-based firewall
      firewalld:
        permanent: yes
        state: enabled
        port: '{{ item }}'
      loop:
        - '25565/tcp'
        - '25565/udp'
    
    - name: Initial server run
      shell: '/usr/bin/java -Xmx1024M -Xms1024M -jar server.jar nogui'
      args: 
        chdir: '{{ mc_server_path }}'
      become: yes
      become_user: minecraft
    
    - name: Touch the server config file
      ansible.builtin.file:
        path: "{{ mc_server_path }}server.conf"
        state: touch
      become: yes
      become_user: minecraft
    
    - name: change the eula file
      lineinfile:
        path: "{{ mc_server_path }}eula.txt"
        regexp: 'eula=false'
        line: 'eula=true'
        state: present
    
    - name: Copy systemd unit to destination directory
      ansible.builtin.copy:
        src:  'minecraft@.service'
        dest: '/etc/systemd/system/'
        owner: minecraft
        group: minecraft
        mode: '0770'

    - name: Enable and start the Minecraft systemd unit
      ansible.builtin.systemd:
        name:  minecraft@oci
        state: started
        enabled: yes
        daemon_reload: yes